platform :ios, '14.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['LD_NO_PIE'] = 'NO'
    end
  end
end
  
target 'Weather' do
  use_frameworks!
  inhibit_all_warnings!
  
    pod 'SwiftGen'
    pod 'SwiftLint'
end

